### ISSUE TITLE
Installing the plugin

### ISSUE THREAD

**Issue by obrsk** [watergis/mapbox-gl-export#1]
Hello. Please tell me how to connect the plugin to the site where mapbox gl is used. Nothing works through npm.

**Comment by JinIgarashi** [comment]
Hi @obrsk, Thank you for trying to use this plugin. Please read README.md how to use it.

first of all, install it by using npm
```
npm i @watergis/mapbox-gl-export --save
```

Then, you can wrote like this.
```js
import MapboxExportControl from "@watergis/mapbox-gl-export";
import '@watergis/mapbox-gl-export/css/styles.css';
import mapboxgl from 'mapbox-gl';

const map = new mapboxgl.Map();
  map.addControl(new MapboxExportControl(), 'top-right');
});
```

Lastly, you can build by `webpack`. Please also have a look of example source code under this repository.

**Comment by obrsk** [comment]
Thanks for the answer.
I've tried installing via npm. The console throws errors. I guess I don't have enough knowledge.
I ended up including bundle.js. For studying. 
Then I tried mpetroff/print-maps. 
It became a little clearer.
Thanks.

**Comment by JinIgarashi** [comment]
@obrsk Which version of Nodejs and npm are you using?
I am currently using 
- Nodejs v12.18.1
- npm 6.14.7

Is following command working?
```
git clone git@github.com:watergis/mapbox-gl-export.git
cd mapbox-gl-export
npm i 
npm run build
npm start
```
access to http://localhost:8080

if everything works, you can see the example website.

**Comment by JinIgarashi** [comment]
@obrsk 
> I've tried installing via npm. The console throws errors. I guess I don't have enough knowledge.

If there is some errors, please also share error messages with me. otherwise I can't tell anything about your issue

**Comment by obrsk** [comment]
I already collected with errors. I got dist and node_modules directories and the example runs on localhost.

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 741 packages from 513 contributors and audited 747 packages in 13.596s

25 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

D:\domains\mapnew>npm run build

> @watergis/mapbox-gl-export@1.1.0 build D:\domains\mapnew
> tsc && webpack --config webpack.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @watergis/mapbox-gl-export@1.1.0 build: `tsc && webpack --config webpack.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @watergis/mapbox-gl-export@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NoName\AppData\Roaming\npm-cache\_logs\2020-10-21T22_14_48_316Z-debug.log

D:\domains\mapnew>npm start

> @watergis/mapbox-gl-export@1.1.0 start D:\domains\mapnew
> webpack-dev-server --open --hot --inline --config webpack.js

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from ./docs
i ｢wdm｣: wait until bundle finished: /
‼ ｢wdm｣: Hash: ca94af6bcdac1cceffe7
Version: webpack 4.44.1
Time: 9216ms
Built at: 2020-10-22 1:15:01
    Asset      Size  Chunks                    Chunk Names
bundle.js  2.89 MiB       0  [emitted]  [big]  main
Entrypoint main [big] = bundle.js
 [1] external "mapboxgl" 42 bytes {0} [built]
 [3] (webpack)/hot/log.js 1.34 KiB {0} [built]
 [5] (webpack)-dev-server/client/utils/log.js 964 bytes {0} [built]
 [6] (webpack)/hot/emitter.js 75 bytes {0} [built]
 [8] ./node_modules/jquery/dist/jquery.js 281 KiB {0} [built]
 [9] ./dist/index.js 4.97 KiB {0} [built]
[10] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./example/index.js 52 bytes {0} [built]
[11] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {0} [built]
[12] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {0} [built]
[14] (webpack)-dev-server/client/socket.js 1.53 KiB {0} [built]
[17] (webpack)-dev-server/client/overlay.js 3.51 KiB {0} [built]
[24] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {0} [built]
[25] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {0} [built]
[38] (webpack)/hot/dev-server.js 1.59 KiB {0} [built]
[40] ./example/index.js 613 bytes {0} [built]
    + 32 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundle.js (2.89 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (2.89 MiB)
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
i ｢wdm｣: Compiled with warnings.`

**Comment by JinIgarashi** [comment]
@obrsk Thank you for sharing error message. It seems happening some error during building process. However, I am not sure what is the exact problem in your environment.

The following repository is using `mapbox-gl-export` by using webpack. It might be helpful for you to know how to use the plugin.
https://github.com/watergis/mapboxgljs-boilerplate
