### ISSUE TITLE
Export to SVG doesn't create a vector file.

### ISSUE THREAD

**Issue by mtdmali** [watergis/mapbox-gl-export#35]
**Describe the bug**
This tool allows you to export a map as an SVG, but it doesn't create a vector file. Instead, it just embeds an `<image>` element with base64 encoded raster data.

**To Reproduce**
1. Go to [the demo site.](https://watergis.github.io/mapbox-gl-export/#12/-1.08551/35.87063)
2. Click on the **Print** button.
3. Export a map as an SVG.
4. Open the exported SVG with a text editor.

**Expected behavior**
I would have expected the SVG to be a vector graphic. The exported SVG is basically useless if it's just a raster image wrapped with an SVG tag.

**Screenshots**
![Screen Shot 2022-04-22 at 11 00 49 AM](https://user-images.githubusercontent.com/35084740/164741173-0e8ca8e1-ff0b-4801-be7e-e0c8b83f134d.png)

**Comment by mtdmali** [comment]
In hindsight, I realize that what I have described may not even be a bug, and my comments specifically are not good examples of open source collaboration.

**Comment by JinIgarashi** [comment]
@mtdmali Yes, I know the issue. To be honest, creating vector format of SVG from mapbox style is too complicated, I gave up developing this and shifted to raster format of SVG instead. However, feel free to fork the repo and make a pull request for the issue. Thanks
