### ISSUE TITLE
Not getting access token

### ISSUE THREAD

**Issue by SamiAlavi** [watergis/mapbox-gl-export#7]
The error I am getting when generating the export is `An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes`, however I have specified the token in my Angular .ts file . Rest of the controls are working fine, only this export control is giving me error.

**Comment by SamiAlavi** [comment]
Found the problem. In `map-generator.js`, it is making a new Map (mapbox-gl), therefore access token is again required for it to work. I added a new key on line 80 `accessToken: YOUR_ACCESS_TOKEN`. Now it is working as it is required. But now the problem is that every developer would have to do this change. This access token should be retrieved from the previous instance of the map (the one where we added control) or there should be a parameter in the constructor `export-control.js` and then passed to  `map-generator.js`.

**Comment by JinIgarashi** [comment]
@SamiAlavi Thank you for reporting the issue. I just have a question to you. Which version of mapbox-gl-js are you using? I guess you use mapbox-gl-js v2?

I am using this plugin for mapbox-gl-js v1, and it works perfectly. mapbox-gl-js became proprietary software since v2, it requires mapbox accessToken all the time. I suspect maybe that changes of v2 affected this plugin.

**Comment by JinIgarashi** [comment]
@SamiAlavi I just added accessToken option into the plugin.
could you check [fix/mapbox-accesstoken](https://github.com/watergis/mapbox-gl-export/tree/fix/mapbox-accesstoken) branch in your environment?

just give accessToken like below.
```js
map.addControl(new MapboxExportControl({
    PageSize: Size.A3,
    PageOrientation: PageOrientation.Portrait,
    Format: Format.PNG,
    DPI: DPI[96]
    accessToken: mapboxgl.accessToken
}), 'top-right');
```

if it can work well on your environment, I will merge it to master branch, then release it as v1.2.2

**Comment by SamiAlavi** [comment]
Yes, I am using `"mapbox-gl": "^2.1.1"`, but the problem isn't because of this version difference. Even after your fix, the error remained. I looked into it more and found out that your current code is working because both the MapboxMap constructors (one in `example/index.js` and other in `map-generator.ts`) are using the same module `node_modules/mapbox-gl`. In my project, or I think any project, the MapboxMap will be using the project's `./node_modules/mapbox-gl` module and your npm package will be using `./node_modules/@watergis/mapbox-gl-export/node_modules/mapbox-gl` module, hence accessToken has to be inserted again into the constructor.

This fix that you created is just setting the `options.accessToken` value, but it is not passing the value to the `MapGenerator` constructor. To further fix this issue, I did the following changes:

- export-control.ts
![1](https://user-images.githubusercontent.com/32700289/111523999-bad33e00-877d-11eb-8e11-e8ce21da124d.PNG)

- map-generator.ts
![2](https://user-images.githubusercontent.com/32700289/111524123-e0f8de00-877d-11eb-97cb-858da0049135.PNG)

**Comment by JinIgarashi** [comment]
@SamiAlavi I am sorry. I forgot to give accesstoken to the instance of mapgenerater. 
I already merged and released as v1.2.2. Could you try to use new version? I hope now it will work well in your environment.

**Comment by SamiAlavi** [comment]
@JinIgarashi Yes, it is now working as expected. Thank you and good work!

**Comment by JinIgarashi** [comment]
@SamiAlavi I just released v1.2.3 for this issue.
https://github.com/watergis/mapbox-gl-export/releases/tag/v1.2.3

I found a way to provide accesstoken instead of adding new option. You can use this plugin same as before without additional token option.

```js
    map.addControl(new MapboxExportControl({
        PageSize: Size.A3,
        PageOrientation: PageOrientation.Portrait,
        Format: Format.PNG,
        DPI: DPI[96],
    }), 'top-right');
```

**Comment by SamiAlavi** [comment]
@JinIgarashi v1.2.3 isn't working for me since I am using mapbox v2 and your library is using mapbox v1, hence the instances of map being created aren't from the same node_modules folder and the accessToken cannot be grabbed just by importing from mapbox-gl. 

![image](https://user-images.githubusercontent.com/32700289/111820874-d23c3380-8903-11eb-96d1-73028f87e863.png)

**Comment by SamiAlavi** [comment]
@JinIgarashi v1.2.3 isn't working for me since I am using mapbox v2 and your library is using mapbox v1, hence the instances of map being created aren't from the same node_modules folder and the accessToken cannot be grabbed just by importing from mapbox-gl. 

![image](https://user-images.githubusercontent.com/32700289/111820874-d23c3380-8903-11eb-96d1-73028f87e863.png)

**Comment by JinIgarashi** [comment]
@SamiAlavi I think Mapbox significantly changed behavior around accesstoken from v1 to v2. This plugin is only supporting for v1 user, I don’t want to add unnecessary token option into constructor of master branch.

But I am thinking I can create another branch for v2 users which is upgraded to v2.

**Comment by SamiAlavi** [comment]
@JinIgarashi Okay great, that will work too most probably. For now I'll be using `mapbox-gl-export 1.2.2` in my project.

**Comment by JinIgarashi** [comment]
@SamiAlavi I created [mbgljs-v2](https://github.com/watergis/mapbox-gl-export/tree/mbgljs-v2) branch and upgraded modules to v2.1.1. Everything is working well without adding new accessToken option.

I think the following code is working properly in v2 environment.
```ts
import { accessToken, Map as MapboxMap } from "mapbox-gl";
```

please check `mbgljs-v2` again. If it cannot work in your environment, I think there might be some problems in your source code.

**Comment by SamiAlavi** [comment]
@JinIgarashi Yes, it is working now, but I still think that adding accessToken option will be better for the long run as you will not have to make changes for every new major version release of mapbox-gl. Mapbox itself using accessToken parameter in https://github.com/mapbox/mapbox-gl-geocoder .

**Comment by JinIgarashi** [comment]
@SamiAlavi Thank you for confirming! If mapbox gl js v2 user can use `mbgljs-v2` branch, I think it would be fine at least. But let me think again about adding accesstoken option...
I close this issue now.

**Comment by JinIgarashi** [comment]
@SamiAlavi now we added accessToken option by https://github.com/watergis/mapbox-gl-export/pull/23
You can use the latest version instead the branch for v2

**Comment by SamiAlavi** [comment]
Thank you. I will update to the latest version.
