### ISSUE TITLE
specify auth headers for mapbox gl js map object

### ISSUE THREAD

**Issue by geoyogesh** [watergis/mapbox-gl-export#9]
I am using mapbox gl js in mapping application it uses vector tiles with custom autheication. 
https://stackoverflow.com/questions/40940860/how-to-specify-authorization-header-for-a-source-in-mapbox-gl-js

Kindly provide ability to pass the pass the  transformRequest callback function just like accesstoken param.

Thanks

**Comment by geoyogesh** [comment]
@JinIgarashi  requested a pull request... that reads the transfrom request object and apply to print mapobject

**Comment by geoyogesh** [comment]
sorry i closed the issue  by mistake

**Comment by JinIgarashi** [comment]
@geoyogesh Thanks! I released [v1.2.4](https://github.com/watergis/mapbox-gl-export/releases/tag/v1.2.4) with your code.
